# Generated by Django 5.2.17 on 2026-10-03 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('orders', '0001_initial'),
        ('predictions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('po_critical', 'PO critical'), ('factory_missed_report', 'Factory missed report'), ('yarn_late', 'Yarn in-house late'), ('inspection_failed', 'Inspection failed'), ('po_at_risk', 'PO at risk'), ('compliance', 'Reporting compliance')], max_length=24, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('threshold', models.JSONField(default=dict)),
                ('default_severity', models.CharField(default='risk', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(db_index=True, max_length=24)),
                ('severity', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('text', models.CharField(max_length=240)),
                ('state', models.CharField(db_index=True, default='open', max_length=10)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(max_length=80, unique=True)),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.factory')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.purchaseorder')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictions.predictionrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['state', 'severity', 'created_at'], name='alerts_aler_state_3b8074_idx')],
            },
        ),
    ]
