# Generated by Django 5.2.17 on 2026-10-03 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_no', models.CharField(db_index=True, max_length=12, unique=True)),
                ('po_date', models.DateField()),
                ('order_qty', models.PositiveIntegerField()),
                ('fob_usd_pc', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fob_value_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('planned_exfactory', models.DateField(db_index=True)),
                ('planned_ship_mode', models.CharField(default='Sea', max_length=8)),
                ('port_of_loading', models.CharField(default='Chattogram', max_length=40)),
                ('destination', models.CharField(max_length=80)),
                ('delivery_terms', models.CharField(default='FOB Chattogram', max_length=40)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='masterdata.factory')),
                ('merchandiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_pos', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.season')),
            ],
        ),
        migrations.CreateModel(
            name='POLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(max_length=40)),
                ('colour_code', models.CharField(max_length=16)),
                ('line_qty', models.PositiveIntegerField()),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orders.purchaseorder')),
            ],
            options={
                'unique_together': {('purchase_order', 'colour_code')},
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_no', models.CharField(db_index=True, max_length=24, unique=True)),
                ('style_name', models.CharField(max_length=120)),
                ('product_type', models.CharField(max_length=60)),
                ('gauge', models.PositiveSmallIntegerField()),
                ('yarn_composition', models.CharField(max_length=80)),
                ('yarn_short', models.CharField(max_length=40)),
                ('wash_required', models.BooleanField(default=False)),
                ('weight_kg_pc', models.DecimalField(decimal_places=3, max_digits=5)),
                ('knitting_minutes_pc', models.DecimalField(decimal_places=2, max_digits=6)),
                ('linking_std_pcs_mc_day', models.PositiveIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.department')),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='orders.style'),
        ),
        migrations.CreateModel(
            name='TAMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField()),
                ('milestone', models.CharField(max_length=40)),
                ('responsible', models.CharField(max_length=60)),
                ('planned_date', models.DateField()),
                ('revised_date', models.DateField(blank=True, null=True)),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=12)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.factory')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_milestones', to='orders.purchaseorder')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='POLineSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=8)),
                ('qty', models.PositiveIntegerField()),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='orders.poline')),
            ],
            options={
                'unique_together': {('po_line', 'size')},
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='masterdata.factory')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='orders.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('purchase_order__isnull', False), ('factory__isnull', True)), models.Q(('purchase_order__isnull', True), ('factory__isnull', False)), _connector='OR'), name='comment_exactly_one_target')],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['factory', 'planned_exfactory'], name='orders_purc_factory_aea007_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['is_open', 'planned_exfactory'], name='orders_purc_is_open_b16de3_idx'),
        ),
        migrations.AddIndex(
            model_name='tamilestone',
            index=models.Index(fields=['purchase_order', 'seq'], name='orders_tami_purchas_168f4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tamilestone',
            unique_together={('purchase_order', 'seq')},
        ),
    ]
