# Generated by Django 5.2.17 on 2026-10-03 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(blank=True, choices=[('order_book', 'Order Book'), ('ta_calendar', 'T&A Calendar'), ('daily_production', 'Factory Daily Production Report'), ('inspection', 'Inspection Log'), ('factory_master', 'Factory Master'), ('shipment', 'Shipment Log')], max_length=24)),
                ('original_filename', models.CharField(max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('detected_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('done', 'done'), ('error', 'error')], db_index=True, default='queued', max_length=12)),
                ('rows_accepted', models.IntegerField(default=0)),
                ('warnings', models.JSONField(default=list)),
                ('errors', models.JSONField(default=list)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('detected_factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.factory')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_id', models.CharField(max_length=20, unique=True)),
                ('inspection_date', models.DateField(db_index=True)),
                ('inspection_type', models.CharField(max_length=24)),
                ('inspector', models.CharField(max_length=60)),
                ('lot_qty', models.PositiveIntegerField()),
                ('aql_level', models.CharField(max_length=20)),
                ('sample_size', models.PositiveIntegerField()),
                ('major_accept', models.PositiveIntegerField()),
                ('critical_found', models.PositiveIntegerField(default=0)),
                ('major_found', models.PositiveIntegerField(default=0)),
                ('minor_found', models.PositiveIntegerField(default=0)),
                ('result', models.CharField(db_index=True, max_length=4)),
                ('main_defect', models.CharField(blank=True, max_length=60)),
                ('measurement_check', models.CharField(default='Pass', max_length=4)),
                ('spec_weight_g', models.PositiveIntegerField(blank=True, null=True)),
                ('avg_weight_g', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.factory')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='orders.purchaseorder')),
                ('upload_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.uploadbatch')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=20, unique=True)),
                ('planned_exfactory', models.DateField()),
                ('actual_exfactory', models.DateField(db_index=True)),
                ('shipped_qty', models.PositiveIntegerField()),
                ('cartons', models.PositiveIntegerField(default=0)),
                ('gross_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ship_mode', models.CharField(max_length=8)),
                ('port_of_loading', models.CharField(max_length=40)),
                ('destination', models.CharField(max_length=80)),
                ('etd', models.DateField(blank=True, null=True)),
                ('eta', models.DateField(blank=True, null=True)),
                ('vessel_flight', models.CharField(blank=True, max_length=60)),
                ('invoice_no', models.CharField(max_length=24)),
                ('invoice_value_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('air_freight_cost_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('freight_borne_by', models.CharField(default='Karbar', max_length=10)),
                ('shipment_status', models.CharField(default='At port', max_length=12)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.factory')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.purchaseorder')),
                ('upload_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.uploadbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['factory', 'actual_exfactory'], name='production__factory_3d4057_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(db_index=True)),
                ('stage', models.CharField(choices=[('knitting', 'Knitting'), ('linking', 'Linking'), ('trimming_mending', 'Trimming & Mending'), ('washing', 'Washing'), ('ironing', 'Ironing'), ('packing', 'Packing')], max_length=16)),
                ('day_pcs', models.IntegerField(default=0)),
                ('cum_pcs', models.IntegerField(default=0)),
                ('machines', models.PositiveIntegerField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterdata.factory')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_production', to='orders.purchaseorder')),
                ('upload_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.uploadbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['purchase_order', 'stage', 'report_date'], name='production__purchas_1ba34e_idx'), models.Index(fields=['factory', 'report_date'], name='production__factory_279485_idx')],
                'unique_together': {('purchase_order', 'stage', 'report_date')},
            },
        ),
    ]
