# Generated by Django 5.2.17 on 2026-10-03 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'holiday',
                'verbose_name_plural': 'holiday calendar',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('kind', models.CharField(max_length=2)),
                ('year', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TATemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngineParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('area', models.CharField(max_length=80)),
                ('district', models.CharField(max_length=40)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('supplier_since', models.DateField(blank=True, null=True)),
                ('gauges', models.CharField(max_length=40)),
                ('linking_machines', models.PositiveIntegerField(default=0)),
                ('washing', models.CharField(default='In-house', max_length=12)),
                ('knitting_shifts', models.PositiveSmallIntegerField(default=2)),
                ('knitting_hours_day', models.PositiveSmallIntegerField(default=20)),
                ('linking_hours_day', models.PositiveSmallIntegerField(default=10)),
                ('workforce', models.PositiveIntegerField(blank=True, null=True)),
                ('certifications', models.CharField(blank=True, max_length=200)),
                ('bsci_rating', models.CharField(blank=True, max_length=2)),
                ('last_social_audit', models.DateField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=80)),
                ('contact_title', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('merchandiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_factories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'factories',
            },
        ),
        migrations.CreateModel(
            name='FactoryMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gauge', models.PositiveSmallIntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='masterdata.factory')),
            ],
            options={
                'unique_together': {('factory', 'gauge')},
            },
        ),
        migrations.CreateModel(
            name='TAMilestoneDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.PositiveSmallIntegerField()),
                ('milestone', models.CharField(max_length=40)),
                ('days_before_exfactory', models.PositiveSmallIntegerField()),
                ('responsible', models.CharField(max_length=60)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='masterdata.tatemplate')),
            ],
            options={
                'ordering': ['seq'],
                'unique_together': {('template', 'seq')},
            },
        ),
    ]
